# Generated by Django 3.2.25 on 2025-04-29 08:27

import CampusMonitor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=CampusMonitor.models.location_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('last_sent_time', models.DateTimeField()),
                ('station_name', models.CharField(max_length=50, unique=True)),
                ('station_display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('x_coord', models.FloatField(blank=True, null=True)),
                ('y_coord', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampusMonitor.location')),
            ],
        ),
        migrations.CreateModel(
            name='StationSensor',
            fields=[
                ('station_sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusMonitor.sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusMonitor.station')),
            ],
        ),
        migrations.CreateModel(
            name='SensorRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=6, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='CampusMonitor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('data_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('station_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusMonitor.stationsensor')),
            ],
        ),
    ]
