# Generated by Django 5.1.6 on 2025-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CampusMonitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="sensor_display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
