# Generated by Django 5.1.6 on 2025-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CampusMonitor", "0002_sensor_sensor_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="description_display",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
